export const APP_CONFIG = {
  name: 'KhataJi Pro',
  version: '1.0.0',
  storageKeys: {
    customers: 'kj_customers',
    transactions: 'kj_transactions',
    itemRates: 'kj_itemRates',
    settings: 'kj_settings',
    pin: 'kj_pin',
    language: 'kj_language',
  },
  currency: 'PKR',
  currencySymbol: 'Rs.',
  quickAmounts: [100, 200, 500, 1000, 2000, 5000],
  paymentMethods: ['cash', 'easypaisa', 'jazzcash', 'bank', 'other'],
};

export const i18n = {
  en: {
    appName: 'KhataJi Pro',
    dashboard: 'Dashboard',
    customers: 'Customers',
    udhaar: 'Udhaar',
    reports: 'Reports',
    settings: 'Settings',
    todayCredit: 'Today Credit',
    todayCollection: 'Collection',
    outstanding: 'Outstanding',
    totalCustomers: 'Customers',
    addCustomer: 'Add Customer',
    addCredit: 'Add Credit',
    addPayment: 'Add Payment',
    recentActivity: 'Recent Activity',
    quickActions: 'Quick Actions',
    search: 'Search customers...',
    noCustomers: 'No customers yet',
    noTransactions: 'No transactions yet',
    credit: 'Credit (Udhaar)',
    debit: 'Payment Received',
    amount: 'Amount',
    note: 'Note (optional)',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    call: 'Call',
    sms: 'SMS',
    pay: 'Pay',
    name: 'Name',
    phone: 'Phone',
    address: 'Address',
    balance: 'Balance',
    totalCredit: 'Total Credit',
    totalDebit: 'Total Paid',
    ledger: 'Ledger',
    all: 'All',
    credits: 'Credits',
    payments: 'Payments',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    welcome: 'Welcome back!',
    shopName: 'Shop Name',
    ownerName: 'Owner Name',
    voiceEntry: 'Voice Entry',
    chatAssistant: 'Chat Assistant',
    insights: 'Insights',
    backup: 'Backup',
    language: 'Language',
    darkMode: 'Dark Mode',
    pin: 'PIN Lock',
    about: 'About',
    totalSales: 'Total Sales',
    totalExpenses: 'Total Expenses',
    profit: 'Profit',
    loss: 'Loss',
    filterBy: 'Filter By',
    export: 'Export',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    confirmDelete: 'Are you sure you want to delete?',
    yes: 'Yes',
    no: 'No',
    selectCustomer: 'Select Customer',
    addItems: 'Add Items',
    quantity: 'Qty',
    rate: 'Rate',
    total: 'Total',
    sendSMS: 'Send SMS reminder',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    easypaisa: 'Easypaisa',
    jazzcash: 'JazzCash',
    bank: 'Bank Transfer',
    other: 'Other',
  },
  ur: {
    appName: 'کھاتا جی پرو',
    dashboard: 'ڈیش بورڈ',
    customers: 'گاہک',
    udhaar: 'ادھار',
    reports: 'رپورٹس',
    settings: 'ترتیبات',
    todayCredit: 'آج کا ادھار',
    todayCollection: 'وصولی',
    outstanding: 'بقایا',
    totalCustomers: 'گاہک',
    addCustomer: 'نیا گاہک',
    addCredit: 'ادھار دیں',
    addPayment: 'رقم وصول کریں',
    recentActivity: 'حالیہ سرگرمی',
    quickActions: 'فوری اعمال',
    search: 'گاہک تلاش کریں...',
    noCustomers: 'ابھی کوئی گاہک نہیں',
    noTransactions: 'ابھی کوئی لین دین نہیں',
    credit: 'ادھار (اُدھار)',
    debit: 'رقم وصول',
    amount: 'رقم',
    note: 'نوٹ (اختیاری)',
    save: 'محفوظ',
    cancel: 'منسوخ',
    delete: 'حذف',
    call: 'کال',
    sms: 'ایس ایم ایس',
    pay: 'ادا',
    name: 'نام',
    phone: 'فون',
    address: 'پتہ',
    balance: 'بقایا',
    totalCredit: 'کل ادھار',
    totalDebit: 'کل ادائیگی',
    ledger: 'کھاتہ',
    all: 'سب',
    credits: 'ادھار',
    payments: 'ادائیگیاں',
    today: 'آج',
    thisWeek: 'اس ہفتے',
    thisMonth: 'اس ماہ',
    welcome: '!خوش آمدید',
    shopName: 'دکان کا نام',
    ownerName: 'مالک کا نام',
    voiceEntry: 'آواز سے اندراج',
    chatAssistant: 'چیٹ اسسٹنٹ',
    insights: 'بصیرت',
    backup: 'بیک اپ',
    language: 'زبان',
    darkMode: 'ڈارک موڈ',
    pin: 'پن لاک',
    about: 'ایپ کے بارے میں',
    totalSales: 'کل فروخت',
    totalExpenses: 'کل اخراجات',
    profit: 'منافع',
    loss: 'نقصان',
    filterBy: 'فلٹر',
    export: 'ایکسپورٹ',
    daily: 'روزانہ',
    weekly: 'ہفتہ وار',
    monthly: 'ماہانہ',
    confirmDelete: 'کیا آپ واقعی حذف کرنا چاہتے ہیں؟',
    yes: 'ہاں',
    no: 'نہیں',
    selectCustomer: 'گاہک منتخب کریں',
    addItems: 'اشیاء شامل کریں',
    quantity: 'مقدار',
    rate: 'ریٹ',
    total: 'کل',
    sendSMS: 'ایس ایم ایس یاد دہانی بھیجیں',
    paymentMethod: 'ادائیگی کا طریقہ',
    cash: 'نقد',
    easypaisa: 'ایزی پیسہ',
    jazzcash: 'جاز کیش',
    bank: 'بینک ٹرانسفر',
    other: 'دیگر',
  },
};
